/* Generated By:JJTree: Do not edit this line. ASTBNFParenthesized.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
namespace CSharpCC.CCTree;

public class ASTBNFParenthesized : CCTreeNode
{
    public ASTBNFParenthesized(int id) : base(id)
    {
    }

    public ASTBNFParenthesized(CCTreeParser p, int id) : base(p, id)
    {
    }


    /** Accept the visitor. **/
    public override object jjtAccept(CCTreeParserVisitor visitor, object data) 
        => visitor.Visit(this, data);
}
/* JavaCC - OriginalChecksum=6fe25af08f1ac052efee21e18f9449dd (do not edit this line) */
