/* Generated By:JJTree: Do not edit this line. ASTBNFZeroOrMore.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
namespace CSharpCC.CCTree;

public class ASTBNFZeroOrMore : CCTreeNode
{
    public ASTBNFZeroOrMore(int id) : base(id)
    {
    }

    public ASTBNFZeroOrMore(CCTreeParser p, int id) : base(p, id)
    {
    }


    /** Accept the visitor. **/
    public override object jjtAccept(CCTreeParserVisitor visitor, object data) 
        => visitor.Visit(this, data);
}
/* JavaCC - OriginalChecksum=a70fd123353fa842ff20ab0affae1cd5 (do not edit this line) */
