/* Generated By:JJTree: Do not edit this line. ASTOptions.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
namespace CSharpCC.CCTree;

public class ASTOptions : CCTreeNode
{
    public ASTOptions(int id) : base(id)
    {
    }

    public ASTOptions(CCTreeParser p, int id):base(p, id)
    {
    }


    /** Accept the visitor. **/
    public override object jjtAccept(CCTreeParserVisitor visitor, object data)
        => visitor.Visit(this, data);
}
/* JavaCC - OriginalChecksum=30aa49e720b353fc345932a3b397455a (do not edit this line) */
