/* Generated By:JJTree: Do not edit this line. ASTREOneOrMore.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
namespace CSharpCC.CCTree;

public class ASTREOneOrMore : CCTreeNode
{
    public ASTREOneOrMore(int id) : base(id)
    {
    }

    public ASTREOneOrMore(CCTreeParser p, int id):base(p,id)
    {
    }


    /** Accept the visitor. **/
    public override object jjtAccept(CCTreeParserVisitor visitor, object data) 
        => visitor.Visit(this, data);
}
/* JavaCC - OriginalChecksum=d8dd7814c374d50f947b0a454cce5d2c (do not edit this line) */
