/* Generated By:JJTree: Do not edit this line. ASTRRepetitionRange.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
namespace CSharpCC.CCTree;

public class ASTRRepetitionRange : CCTreeNode
{
    public ASTRRepetitionRange(int id) : base(id)
    {
    }

    public ASTRRepetitionRange(CCTreeParser p, int id) : base(p, id)
    {
    }


    /** Accept the visitor. **/
    public override object jjtAccept(CCTreeParserVisitor visitor, object data)
        => visitor.Visit(this, data);
}
/* JavaCC - OriginalChecksum=d3ae5251edbeb55e9e6e051b8dd48bf6 (do not edit this line) */
