/* Generated By:JJTree: Do not edit this line. ASTRESequence.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
namespace CSharpCC.CCTree;

public class ASTRESequence : CCTreeNode
{
    public ASTRESequence(int id) : base(id)
    {
    }

    public ASTRESequence(CCTreeParser p, int id) : base(p, id)
    {
    }


    /** Accept the visitor. **/
    public override object jjtAccept(CCTreeParserVisitor visitor, object data)
        => visitor.Visit(this, data);
}
/* JavaCC - OriginalChecksum=4eeafa01418b8ce2f8b7ef9966338e73 (do not edit this line) */
