/* Generated By:JJTree: Do not edit this line. ASTREChoice.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
namespace CSharpCC.CCTree;

public class ASTREChoice : CCTreeNode
{
    public ASTREChoice(int id) : base(id)
    {
    }

    public ASTREChoice(CCTreeParser p, int id) : base(p, id)
    {
    }


    /** Accept the visitor. **/
    public override object jjtAccept(CCTreeParserVisitor visitor, object data)
       => visitor.Visit(this, data);   
}
/* JavaCC - OriginalChecksum=ca959d0dc576808b2ba5ef90e0c68c74 (do not edit this line) */
