/* Generated By:JJTree: Do not edit this line. ASTREZeroOrOne.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
namespace CSharpCC.CCTree;

public class ASTREZeroOrOne : CCTreeNode
{
    public ASTREZeroOrOne(int id) : base(id)
    {
    }

    public ASTREZeroOrOne(CCTreeParser p, int id) : base(p, id)
    {
    }


    /** Accept the visitor. **/
    public override object jjtAccept(CCTreeParserVisitor visitor, object data)
        => visitor.Visit(this, data);
}
/* JavaCC - OriginalChecksum=8652fde1d0c22ed8219c340f4cc6d31c (do not edit this line) */
