/* Generated By:JavaCC: Do not edit this line. TokenMgrError.java Version 5.0 */
/* JavaCCOptions: */
namespace CSharpCC.CCTree;

public class Error : Exception
{
    public Error() : base() { }
    public Error(string? message) : base(message)
    {
    }
}