/* Generated By:JJTree: Do not edit this line. ASTBNFOneOrMore.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
namespace org.javacc.jjtree;

public class ASTBNFOneOrMore : JJTreeNode
{
    public ASTBNFOneOrMore(int id) : base(id)
    {
    }

    public ASTBNFOneOrMore(JJTreeParser p, int id) : base(p, id)
    {
    }


    /** Accept the visitor. **/
    public override object jjtAccept(JJTreeParserVisitor visitor, object data)
        => visitor.Visit(this, data);
}
/* JavaCC - OriginalChecksum=ba509f753bd5e4d1bd507fdc6dceb243 (do not edit this line) */
