/* Generated By:JJTree: Do not edit this line. ASTBNFTryBlock.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
namespace org.javacc.jjtree;

public
class ASTBNFTryBlock : JJTreeNode
{
    public ASTBNFTryBlock(int id) : base(id)
    {
    }

    public ASTBNFTryBlock(JJTreeParser p, int id) : base(p, id)
    {
    }


    /** Accept the visitor. **/
    public Object jjtAccept(JJTreeParserVisitor visitor, Object data)
    {
        return visitor.visit(this, data);
    }
}
/* JavaCC - OriginalChecksum=54b51e7e9038806bbf804197f88beaf7 (do not edit this line) */
