/* Generated By:JJTree: Do not edit this line. ASTBNFZeroOrOne.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
namespace org.javacc.jjtree;

public class ASTBNFZeroOrOne : JJTreeNode
{
    public ASTBNFZeroOrOne(int id) : base(id)
    {
    }

    public ASTBNFZeroOrOne(JJTreeParser p, int id) : base(p, id)
    {
    }


    /** Accept the visitor. **/
    public override object jjtAccept(JJTreeParserVisitor visitor, object data) 
        => visitor.Visit(this, data);
}
/* JavaCC - OriginalChecksum=29f0f3c6e87575930f47dbfdc83617ea (do not edit this line) */
