/* Generated By:JJTree: Do not edit this line. ASTBNFLookahead.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
namespace org.javacc.jjtree;

public class ASTBNFLookahead : JJTreeNode
{
    public ASTBNFLookahead(int id) : base(id)
    {
    }

    public ASTBNFLookahead(JJTreeParser p, int id) : base(p, id)
    {
    }


    /** Accept the visitor. **/
    public override object jjtAccept(JJTreeParserVisitor visitor, object data)
    {
        return visitor.visit(this, data);
    }
}
/* JavaCC - OriginalChecksum=d4584298bda5bb506801d1a537cf1471 (do not edit this line) */
