/* Generated By:JJTree: Do not edit this line. ASTBNFParenthesized.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
namespace org.javacc.jjtree;

public class ASTBNFParenthesized : JJTreeNode
{
    public ASTBNFParenthesized(int id) : base(id)
    {
    }

    public ASTBNFParenthesized(JJTreeParser p, int id) : base(p, id)
    {
    }


    /** Accept the visitor. **/
    public override object jjtAccept(JJTreeParserVisitor visitor, object data)
    {
        return visitor.visit(this, data);
    }
}
/* JavaCC - OriginalChecksum=6fe25af08f1ac052efee21e18f9449dd (do not edit this line) */
