/* Generated By:JJTree: Do not edit this line. ASTBNFNonTerminal.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
namespace org.javacc.jjtree;

public class ASTBNFNonTerminal : JJTreeNode
{
    public ASTBNFNonTerminal(int id) : base(id)
    {
    }

    public ASTBNFNonTerminal(JJTreeParser p, int id) : base(p, id)
    {
    }


    /** Accept the visitor. **/
    public override object jjtAccept(JJTreeParserVisitor visitor, object data) 
        => visitor.Visit(this, data);
}
/* JavaCC - OriginalChecksum=680f159c6e10c833981af10c500e5d27 (do not edit this line) */
