/* Generated By:JJTree: Do not edit this line. ASTCharDescriptor.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
namespace org.javacc.jjtree;

public class ASTCharDescriptor : JJTreeNode
{
    public ASTCharDescriptor(int id) : base(id)
    {
    }

    public ASTCharDescriptor(JJTreeParser p, int id) : base(p, id)
    {
    }


    /** Accept the visitor. **/
    public Object jjtAccept(JJTreeParserVisitor visitor, Object data)
    {
        return visitor.visit(this, data);
    }
}
/* JavaCC - OriginalChecksum=34443ffa81002e24122bb38aa8cf7556 (do not edit this line) */
