/* Generated By:JJTree: Do not edit this line. ASTREZeroOrMore.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
namespace org.javacc.jjtree;

public class ASTREZeroOrMore : JJTreeNode
{
    public ASTREZeroOrMore(int id) : base(id)
    {
    }

    public ASTREZeroOrMore(JJTreeParser p, int id) : base(p, id)
    {
    }


    /** Accept the visitor. **/
    public Object jjtAccept(JJTreeParserVisitor visitor, Object data)
    {
        return visitor.visit(this, data);
    }
}
/* JavaCC - OriginalChecksum=d803481ed1b50699162caf15e74fa188 (do not edit this line) */
