/* Generated By:JJTree: Do not edit this line. ASTRE.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
namespace org.javacc.jjtree;

public class ASTRE : JJTreeNode
{
    public ASTRE(int id) : base(id)
    {
    }

    public ASTRE(JJTreeParser p, int id) : base(p, id)
    {
    }


    /** Accept the visitor. **/
    public override object jjtAccept(JJTreeParserVisitor visitor, object data)
        => visitor.Visit(this, data);
}
/* JavaCC - OriginalChecksum=f07e0df6cddec7e74dda5f201d1fb258 (do not edit this line) */
