/* Generated By:JJTree: Do not edit this line. ASTRECharList.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
namespace org.javacc.jjtree;

public class ASTRECharList : JJTreeNode
{
    public ASTRECharList(int id) : base(id)
    {
    }

    public ASTRECharList(JJTreeParser p, int id) : base(p, id)
    {
    }


    /** Accept the visitor. **/
    public override object jjtAccept(JJTreeParserVisitor visitor, object data)
    => visitor.visit(this, data);
}
/* JavaCC - OriginalChecksum=6b63308e55dc6c41b35c42beb30f121c (do not edit this line) */
