/* Generated By:JJTree: Do not edit this line. ASTRRepetitionRange.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
namespace org.javacc.jjtree;

public class ASTRRepetitionRange : JJTreeNode
{
    public ASTRRepetitionRange(int id) : base(id)
    {
    }

    public ASTRRepetitionRange(JJTreeParser p, int id) : base(p, id)
    {
    }


    /** Accept the visitor. **/
    public Object jjtAccept(JJTreeParserVisitor visitor, Object data)
    {
        return visitor.visit(this, data);
    }
}
/* JavaCC - OriginalChecksum=d3ae5251edbeb55e9e6e051b8dd48bf6 (do not edit this line) */
