/* Generated By:JJTree: Do not edit this line. ASTREReference.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
namespace org.javacc.jjtree;

public class ASTREReference : JJTreeNode
{
    public ASTREReference(int id) : base(id)
    {
    }

    public ASTREReference(JJTreeParser p, int id) : base(p, id)
    {
    }


    /** Accept the visitor. **/
    public Object jjtAccept(JJTreeParserVisitor visitor, Object data)
    {
        return visitor.visit(this, data);
    }
}
/* JavaCC - OriginalChecksum=4410f4afb6ff9b68c538695719fc7ab8 (do not edit this line) */
