/* Generated By:JJTree: Do not edit this line. ASTREZeroOrOne.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
namespace org.javacc.jjtree;

public class ASTREZeroOrOne : JJTreeNode
{
    public ASTREZeroOrOne(int id) : base(id)
    {
    }

    public ASTREZeroOrOne(JJTreeParser p, int id) : base(p, id)
    {
    }


    /** Accept the visitor. **/
    public override object jjtAccept(JJTreeParserVisitor visitor, object data)
    {
        return visitor.visit(this, data);
    }
}
/* JavaCC - OriginalChecksum=8652fde1d0c22ed8219c340f4cc6d31c (do not edit this line) */
