/* Generated By:JJTree: Do not edit this line. ASTRESpec.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
namespace org.javacc.jjtree;

public class ASTRESpec : JJTreeNode
{
    public ASTRESpec(int id) : base(id)
    {
    }

    public ASTRESpec(JJTreeParser p, int id) : base(p, id)
    {
    }


    /** Accept the visitor. **/
    public override object jjtAccept(JJTreeParserVisitor visitor, object data) 
        => visitor.Visit(this, data);
}
/* JavaCC - OriginalChecksum=0ee752b4ed8ea3ab9419f5b92e6a94cc (do not edit this line) */
