/* Generated By:JJTree: Do not edit this line. ASTREParenthesized.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
namespace org.javacc.jjtree;

public class ASTREParenthesized : JJTreeNode
{
    public ASTREParenthesized(int id) : base(id)
    {
    }

    public ASTREParenthesized(JJTreeParser p, int id) : base(p, id)
    {
    }


    /** Accept the visitor. **/
    public override object jjtAccept(JJTreeParserVisitor visitor, object data) 
        => visitor.visit(this, data);
}
/* JavaCC - OriginalChecksum=8970d8eec79e865b4d3da4e675e358d4 (do not edit this line) */
