/* Generated By:JJTree: Do not edit this line. ASTTokenDecls.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
namespace org.javacc.jjtree;

public class ASTTokenDecls : JJTreeNode
{
    public ASTTokenDecls(int id) : base(id)
    {
    }

    public ASTTokenDecls(JJTreeParser p, int id) : base(p, id)
    {
    }


    /** Accept the visitor. **/
    public override object jjtAccept(JJTreeParserVisitor visitor, object data) 
        => visitor.Visit(this, data);
}
/* JavaCC - OriginalChecksum=ee1e62f722994c0e858d5686f515ecfe (do not edit this line) */
