/* Generated By:JavaCC: Do not edit this line. TokenMgrError.java Version 5.0 */
/* JavaCCOptions: */
namespace org.javacc.jjtree;

public class Error : Exception
{
    public Error(string? message) : base(message)
    {
    }
}