/* Generated By:JJTree&JavaCC: Do not edit this line. JJTreeParserConstants.java */
namespace org.javacc.jjtree;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface JJTreeParserConstants
{

    /** End of File. */
    const int EOF = 0;
    /** RegularExpression Id. */
    const int _LOOKAHEAD = 1;
    /** RegularExpression Id. */
    const int _IGNORE_CASE = 2;
    /** RegularExpression Id. */
    const int _PARSER_BEGIN = 3;
    /** RegularExpression Id. */
    const int _PARSER_END = 4;
    /** RegularExpression Id. */
    const int _JAVACODE = 5;
    /** RegularExpression Id. */
    const int _TOKEN = 6;
    /** RegularExpression Id. */
    const int _SPECIAL_TOKEN = 7;
    /** RegularExpression Id. */
    const int _MORE = 8;
    /** RegularExpression Id. */
    const int _SKIP = 9;
    /** RegularExpression Id. */
    const int _TOKEN_MGR_DECLS = 10;
    /** RegularExpression Id. */
    const int _EOF = 11;
    /** RegularExpression Id. */
    const int SINGLE_LINE_COMMENT = 20;
    /** RegularExpression Id. */
    const int FORMAL_COMMENT = 21;
    /** RegularExpression Id. */
    const int MULTI_LINE_COMMENT = 22;
    /** RegularExpression Id. */
    const int ABSTRACT = 24;
    /** RegularExpression Id. */
    const int BOOLEAN = 25;
    /** RegularExpression Id. */
    const int BREAK = 26;
    /** RegularExpression Id. */
    const int BYTE = 27;
    /** RegularExpression Id. */
    const int CASE = 28;
    /** RegularExpression Id. */
    const int CATCH = 29;
    /** RegularExpression Id. */
    const int CHAR = 30;
    /** RegularExpression Id. */
    const int CLASS = 31;
    /** RegularExpression Id. */
    const int CONST = 32;
    /** RegularExpression Id. */
    const int CONTINUE = 33;
    /** RegularExpression Id. */
    const int _DEFAULT = 34;
    /** RegularExpression Id. */
    const int DO = 35;
    /** RegularExpression Id. */
    const int DOUBLE = 36;
    /** RegularExpression Id. */
    const int ELSE = 37;
    /** RegularExpression Id. */
    const int EXTENDS = 38;
    /** RegularExpression Id. */
    const int FALSE = 39;
    /** RegularExpression Id. */
    const int FINAL = 40;
    /** RegularExpression Id. */
    const int FINALLY = 41;
    /** RegularExpression Id. */
    const int FLOAT = 42;
    /** RegularExpression Id. */
    const int FOR = 43;
    /** RegularExpression Id. */
    const int GOTO = 44;
    /** RegularExpression Id. */
    const int IF = 45;
    /** RegularExpression Id. */
    const int IMPLEMENTS = 46;
    /** RegularExpression Id. */
    const int IMPORT = 47;
    /** RegularExpression Id. */
    const int INSTANCEOF = 48;
    /** RegularExpression Id. */
    const int INT = 49;
    /** RegularExpression Id. */
    const int INTERFACE = 50;
    /** RegularExpression Id. */
    const int LONG = 51;
    /** RegularExpression Id. */
    const int NATIVE = 52;
    /** RegularExpression Id. */
    const int NEW = 53;
    /** RegularExpression Id. */
    const int NULL = 54;
    /** RegularExpression Id. */
    const int PACKAGE = 55;
    /** RegularExpression Id. */
    const int PRIVATE = 56;
    /** RegularExpression Id. */
    const int PROTECTED = 57;
    /** RegularExpression Id. */
    const int PUBLIC = 58;
    /** RegularExpression Id. */
    const int RETURN = 59;
    /** RegularExpression Id. */
    const int SHORT = 60;
    /** RegularExpression Id. */
    const int STATIC = 61;
    /** RegularExpression Id. */
    const int SUPER = 62;
    /** RegularExpression Id. */
    const int SWITCH = 63;
    /** RegularExpression Id. */
    const int SYNCHRONIZED = 64;
    /** RegularExpression Id. */
    const int THIS = 65;
    /** RegularExpression Id. */
    const int THROW = 66;
    /** RegularExpression Id. */
    const int THROWS = 67;
    /** RegularExpression Id. */
    const int TRANSIENT = 68;
    /** RegularExpression Id. */
    const int TRUE = 69;
    /** RegularExpression Id. */
    const int TRY = 70;
    /** RegularExpression Id. */
    const int VOID = 71;
    /** RegularExpression Id. */
    const int VOLATILE = 72;
    /** RegularExpression Id. */
    const int WHILE = 73;
    /** RegularExpression Id. */
    const int INTEGER_LITERAL = 74;
    /** RegularExpression Id. */
    const int DECIMAL_LITERAL = 75;
    /** RegularExpression Id. */
    const int HEX_LITERAL = 76;
    /** RegularExpression Id. */
    const int OCTAL_LITERAL = 77;
    /** RegularExpression Id. */
    const int FLOATING_POINT_LITERAL = 78;
    /** RegularExpression Id. */
    const int DECIMAL_FLOATING_POINT_LITERAL = 79;
    /** RegularExpression Id. */
    const int DECIMAL_EXPONENT = 80;
    /** RegularExpression Id. */
    const int HEXADECIMAL_FLOATING_POINT_LITERAL = 81;
    /** RegularExpression Id. */
    const int HEXADECIMAL_EXPONENT = 82;
    /** RegularExpression Id. */
    const int CHARACTER_LITERAL = 83;
    /** RegularExpression Id. */
    const int STRING_LITERAL = 84;
    /** RegularExpression Id. */
    const int LPAREN = 85;
    /** RegularExpression Id. */
    const int RPAREN = 86;
    /** RegularExpression Id. */
    const int LBRACE = 87;
    /** RegularExpression Id. */
    const int RBRACE = 88;
    /** RegularExpression Id. */
    const int LBRACKET = 89;
    /** RegularExpression Id. */
    const int RBRACKET = 90;
    /** RegularExpression Id. */
    const int SEMICOLON = 91;
    /** RegularExpression Id. */
    const int COMMA = 92;
    /** RegularExpression Id. */
    const int DOT = 93;
    /** RegularExpression Id. */
    const int HASH = 94;
    /** RegularExpression Id. */
    const int ASSIGN = 95;
    /** RegularExpression Id. */
    const int LT = 96;
    /** RegularExpression Id. */
    const int BANG = 97;
    /** RegularExpression Id. */
    const int TILDE = 98;
    /** RegularExpression Id. */
    const int HOOK = 99;
    /** RegularExpression Id. */
    const int COLON = 100;
    /** RegularExpression Id. */
    const int DOUBLECOLON = 101;
    /** RegularExpression Id. */
    const int EQ = 102;
    /** RegularExpression Id. */
    const int LE = 103;
    /** RegularExpression Id. */
    const int GE = 104;
    /** RegularExpression Id. */
    const int NE = 105;
    /** RegularExpression Id. */
    const int SC_OR = 106;
    /** RegularExpression Id. */
    const int SC_AND = 107;
    /** RegularExpression Id. */
    const int INCR = 108;
    /** RegularExpression Id. */
    const int DECR = 109;
    /** RegularExpression Id. */
    const int PLUS = 110;
    /** RegularExpression Id. */
    const int MINUS = 111;
    /** RegularExpression Id. */
    const int STAR = 112;
    /** RegularExpression Id. */
    const int SLASH = 113;
    /** RegularExpression Id. */
    const int BIT_AND = 114;
    /** RegularExpression Id. */
    const int BIT_OR = 115;
    /** RegularExpression Id. */
    const int XOR = 116;
    /** RegularExpression Id. */
    const int REM = 117;
    /** RegularExpression Id. */
    const int PLUSASSIGN = 118;
    /** RegularExpression Id. */
    const int MINUSASSIGN = 119;
    /** RegularExpression Id. */
    const int STARASSIGN = 120;
    /** RegularExpression Id. */
    const int SLASHASSIGN = 121;
    /** RegularExpression Id. */
    const int ANDASSIGN = 122;
    /** RegularExpression Id. */
    const int ORASSIGN = 123;
    /** RegularExpression Id. */
    const int XORASSIGN = 124;
    /** RegularExpression Id. */
    const int REMASSIGN = 125;
    /** RegularExpression Id. */
    const int RUNSIGNEDSHIFT = 126;
    /** RegularExpression Id. */
    const int RSIGNEDSHIFT = 127;
    /** RegularExpression Id. */
    const int GT = 128;
    /** RegularExpression Id. */
    const int IDENTIFIER = 140;
    /** RegularExpression Id. */
    const int LETTER = 141;
    /** RegularExpression Id. */
    const int PART_LETTER = 142;

    /** Lexical state. */
    const int DEFAULT = 0;
    /** Lexical state. */
    const int IN_SINGLE_LINE_COMMENT = 1;
    /** Lexical state. */
    const int IN_FORMAL_COMMENT = 2;
    /** Lexical state. */
    const int IN_MULTI_LINE_COMMENT = 3;

    /** Literal token values. */
    static readonly string[] tokenImage = {
    "<EOF>",
    "\"LOOKAHEAD\"",
    "\"IGNORE_CASE\"",
    "\"PARSER_BEGIN\"",
    "\"PARSER_END\"",
    "\"JAVACODE\"",
    "\"TOKEN\"",
    "\"SPECIAL_TOKEN\"",
    "\"MORE\"",
    "\"SKIP\"",
    "\"TOKEN_MGR_DECLS\"",
    "\"EOF\"",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "\"//\"",
    "<token of kind 18>",
    "\"/*\"",
    "<SINGLE_LINE_COMMENT>",
    "\"*/\"",
    "\"*/\"",
    "<token of kind 23>",
    "\"abstract\"",
    "\"boolean\"",
    "\"break\"",
    "\"byte\"",
    "\"case\"",
    "\"catch\"",
    "\"char\"",
    "\"class\"",
    "\"const\"",
    "\"continue\"",
    "\"default\"",
    "\"do\"",
    "\"double\"",
    "\"else\"",
    "\"extends\"",
    "\"false\"",
    "\"final\"",
    "\"finally\"",
    "\"float\"",
    "\"for\"",
    "\"goto\"",
    "\"if\"",
    "\"implements\"",
    "\"import\"",
    "\"instanceof\"",
    "\"int\"",
    "\"interface\"",
    "\"long\"",
    "\"native\"",
    "\"new\"",
    "\"null\"",
    "\"package\"",
    "\"private\"",
    "\"protected\"",
    "\"public\"",
    "\"return\"",
    "\"short\"",
    "\"static\"",
    "\"super\"",
    "\"switch\"",
    "\"synchronized\"",
    "\"this\"",
    "\"throw\"",
    "\"throws\"",
    "\"transient\"",
    "\"true\"",
    "\"try\"",
    "\"void\"",
    "\"volatile\"",
    "\"while\"",
    "<INTEGER_LITERAL>",
    "<DECIMAL_LITERAL>",
    "<HEX_LITERAL>",
    "<OCTAL_LITERAL>",
    "<FLOATING_POINT_LITERAL>",
    "<DECIMAL_FLOATING_POINT_LITERAL>",
    "<DECIMAL_EXPONENT>",
    "<HEXADECIMAL_FLOATING_POINT_LITERAL>",
    "<HEXADECIMAL_EXPONENT>",
    "<CHARACTER_LITERAL>",
    "<STRING_LITERAL>",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\";\"",
    "\",\"",
    "\".\"",
    "\"#\"",
    "\"=\"",
    "\"<\"",
    "\"!\"",
    "\"~\"",
    "\"?\"",
    "\":\"",
    "\"::\"",
    "\"==\"",
    "\"<=\"",
    "\">=\"",
    "\"!=\"",
    "\"||\"",
    "\"&&\"",
    "\"++\"",
    "\"--\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"&\"",
    "\"|\"",
    "\"^\"",
    "\"%\"",
    "\"+=\"",
    "\"-=\"",
    "\"*=\"",
    "\"/=\"",
    "\"&=\"",
    "\"|=\"",
    "\"^=\"",
    "\"%=\"",
    "\">>>\"",
    "\">>\"",
    "\">\"",
    "\"strictfp\"",
    "\"enum\"",
    "\"...\"",
    "\"template\"",
    "\"typename\"",
    "\"<<=\"",
    "\">>=\"",
    "\">>>=\"",
    "\"<<\"",
    "\"assert\"",
    "\"@\"",
    "<IDENTIFIER>",
    "<LETTER>",
    "<PART_LETTER>",
  };

}
