/* Generated By:JJTree&JavaCC: Do not edit this line. JJTreeParser.java */
namespace org.javacc.jjtree;

public class RuntimeException : Exception
{
    public RuntimeException() { }
    public RuntimeException(string message) : base(message) { }
    public RuntimeException(string message, Exception inner) : base(message, inner) { }
}